language: csharp
solution: ./src/Global.Configuration.Dal.sln
install:
  - nuget restore ./src/Global.Configuration.Dal.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner

script:
  - msbuild /p:Configuration=Release solution-name.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./src/Global.Configuration.Dal.Tests/bin/Release/Global.Configuration.Dal.Tests.dll