dist: trusty
addons:
  sonarcloud:
    organization: "creatio-labs"
    token:
      secure: "xFEmjuUkQDOrGDVq9x1NVx7oPSmhIf7lHRhUotnZ8uvK4Mvb6WH+hj9ch8rad2/33Z0i394eyaNI6JCjhUFnw76timYfdVzA1WNT+iDpH/COVln95cz3ZFaJFwFJqAbUwZMbTegB0p7DKUyZtjpoY16TZbQB0qrtvZEh9N0B7ICdkNrtTH6tnymPjk/uOj1EEc/7LJg3vUYz+uNWynjUN8SakqKGDWLL59TqAb3E8psfsZGIQTI69qLDMwquxWGSC4/DslHX545wnbD9LxMZ2WqMDENhK318LUCn831JrXk1DhWyvcr1pYqso47yLeq3ix+Mh5FUT8epPPoLtTVbZC2KA3h1acV1Z52OBVHviOlklZB+qBnZhLb5ZT1MS4JA7+kadjhMF6isYCL2wOuKYDL9lMSBcT3xq4B+RcMXifgYg6bWpJdM5hjSOAMqB5Vxy5XKhNIwcZmMbIo7lRZ3DFwj/Ivg9PpEagXs4bPsPBWJO1eHlOnI7DKI83a17dQ76al8yNA5Njt4jVpUyQXQw0OdeUwj4yC78fw+JipyXza+xuaXsDgFXTFT9ubL3UP9nSPOWL+uE+N0GJ3G6gpYh5QvFhdkcIMQKNW8GTZzCh3s8eTb6RqGccFSyfOgxGZuWMkVAeNIhaY37uEb2A/POFRXA3S5Nleo7Gm4BIdxr5U="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner

env:
  global:
    secure: YFn7uesM7tmNS9I/oBpyHx4d+WbuvhRSiiKnRN05C7h6dv/imDaXEl24xXxysos/JK7N2m2/4mtG2hBgYIMQGzpMr9TtUltsF1MsTkIaRCW65NfPkh5IvtRnBdZvfICrIHga9eQNhfB8TIGjmjihLHeyVXLRpcicJRbIiNDDOzzTMk9o+7Ta0fugF+cEZgjALiPoH/MgWWMwiFIn3bSAn7x8dqooOgF/pHJVwTeIzoc0WCtuxhteJuGoCAodgYcY2TJEbhZw3EdH+i9KAUMigVKtlrCVouNrfOsuDdtpoRx/qqx4HJwCAc8nIk8sIR2RU1obPSnNH4nS8hnNodsHbK5Cu5jIRBKbVpOAVWkuZCmRyejz8Um9dKekqWVgZamaoUeoy8cgyM9cJXnQvV+S3XrIDvoAxD2dfdeTEkoXaA/GF9DCoRmC4Vtzx5DLuOkb/2dVe1gaee4VLGRt8cqx/UnhMo7IeiJJqU1heztXU1YVA0zqFA+lmgBKKr0AFLpQ5S0Qbxqeklgy7mcU3QX+n1eJfan+DEzJmMjX/D5bK07dWW23EY34E+4TBpPtxknjuxvef55JWNA9gGHNpsXlPrXcR8dfuieNY3CuFjlMxITDklF355vKB1VzMxJ9m+ayx75wGDECdRSalbW5LCM++9yuECblvMdLDV8R7lhjjDU=
