language: csharp
solution: src/Global.Configuration.Dal.sln
addons:
  sonarcloud:
    organization: "creatio-labs"

before_install:
  - bash ./tools/travis-install.sh

install:
  - nuget restore ./src/Global.Configuration.Dal.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory tools/testrunner

script:
  #- msbuild /p:Configuration=Release ./src/Global.Configuration.Dal.sln
  #- mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./src/Global.Configuration.Dal.Tests/bin/Release/Global.Configuration.Dal.Tests.dll
  - bash ./tools/travis-build.sh